# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\"/\n\x10ListTermsRequest\x12\x0c\n\x04skip\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"O\n\x11ListTermsResponse\x12%\n\x05terms\x18\x01 \x03(\x0b\x32\x16.glossary.TermResponse\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\"!\n\x0eGetTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"]\n\x11\x43reateTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x10\n\x08\x65xamples\x18\x04 \x01(\t\"]\n\x11UpdateTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x10\n\x08\x65xamples\x18\x04 \x01(\t\"$\n\x11\x44\x65leteTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"\x80\x01\n\x0cTermResponse\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x10\n\x08\x65xamples\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xdf\x02\n\x0fGlossaryService\x12\x44\n\tListTerms\x12\x1a.glossary.ListTermsRequest\x1a\x1b.glossary.ListTermsResponse\x12;\n\x07GetTerm\x12\x18.glossary.GetTermRequest\x1a\x16.glossary.TermResponse\x12\x41\n\nCreateTerm\x12\x1b.glossary.CreateTermRequest\x1a\x16.glossary.TermResponse\x12\x41\n\nUpdateTerm\x12\x1b.glossary.UpdateTermRequest\x1a\x16.glossary.TermResponse\x12\x43\n\nDeleteTerm\x12\x1b.glossary.DeleteTermRequest\x1a\x18.glossary.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTTERMSREQUEST']._serialized_start=28
  _globals['_LISTTERMSREQUEST']._serialized_end=75
  _globals['_LISTTERMSRESPONSE']._serialized_start=77
  _globals['_LISTTERMSRESPONSE']._serialized_end=156
  _globals['_GETTERMREQUEST']._serialized_start=158
  _globals['_GETTERMREQUEST']._serialized_end=191
  _globals['_CREATETERMREQUEST']._serialized_start=193
  _globals['_CREATETERMREQUEST']._serialized_end=286
  _globals['_UPDATETERMREQUEST']._serialized_start=288
  _globals['_UPDATETERMREQUEST']._serialized_end=381
  _globals['_DELETETERMREQUEST']._serialized_start=383
  _globals['_DELETETERMREQUEST']._serialized_end=419
  _globals['_TERMRESPONSE']._serialized_start=422
  _globals['_TERMRESPONSE']._serialized_end=550
  _globals['_DELETERESPONSE']._serialized_start=552
  _globals['_DELETERESPONSE']._serialized_end=602
  _globals['_GLOSSARYSERVICE']._serialized_start=605
  _globals['_GLOSSARYSERVICE']._serialized_end=956
# @@protoc_insertion_point(module_scope)
